---
- name: Verify
  hosts: localhost
  vars_files:
    - ../../vars/main.yml
  tasks:
    - name: Check if the .fzf directory exists
      stat:
        path: "{{ ansible_fzf_user_home }}/.fzf"
      register: fzf_directory_facts

    - name: Fail if .fzf directory does not exist
      fail:
        msg: "fzf cli does not exist."
      when: not fzf_directory_facts.stat.exists

    - name: Check if the fzf binary exists
      stat:
        path: "{{ ansible_fzf_user_home }}/.fzf/bin/fzf"
      register: fzf_binary_facts

    - name: Fail if fzf binary does not exist
      fail:
        msg: "fzf binary does not exist."
      when: not fzf_binary_facts.stat.exists
